# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jacobians blog
email: admin@karengnayong.com
description: >
this blog will mainly be about code building
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.jacobian.xyz" # the base hostname & protocol for your site
twitter_username: jacobian64
github_username:  jacobian64

# Build settings
markdown: kramdown
